# =============================================================================
#  Workflow to release on IPFS
# =============================================================================
name: Release

on:
  workflow_dispatch:
  release:

jobs:
  ipfsrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload to IPFS via Pinata
        uses: aquiladev/ipfs-action@master
        id: pinata
        with:
          path: ./query.json
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: qiitask-query
          verbose: true

      - name: Echo CID
        run: |
          echo ${{ steps.pinata.outputs.hash }} > ipfs_cid.txt

      - name: Upload binaries to release
            uses: svenstaro/upload-release-action@v2
            with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: ipfs_cid.txt
              asset_name: ipfs_cid.txt
              tag: ${{ github.ref }}
              overwrite: true
              body: "IPFS CID: ${{ steps.pinata.outputs.hash }}"
